"""marketplace workflow foundation

Revision ID: 3ce10ed55bd1
Revises: 94515b6543dc
Create Date: 2026-08-28 01:31:27.720501
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '3ce10ed55bd1'
down_revision: Union[str, Sequence[str], None] = '94515b6543dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)

    op.create_table('candidate_availability',
    sa.Column('candidate_profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by', sa.String(length=40), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_profile_id')
    )
    with op.batch_alter_table('candidate_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_availability_status'), ['status'], unique=False)

    op.create_table('candidate_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_profile_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_profile_id', 'requirement_id')
    )
    with op.batch_alter_table('candidate_interests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_interests_candidate_profile_id'), ['candidate_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_interests_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_interests_status'), ['status'], unique=False)

    op.create_table('requirement_commercial_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payout_model', sa.String(length=30), nullable=False),
    sa.Column('payout_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_trigger', sa.String(length=120), nullable=False),
    sa.Column('payment_timeline_days', sa.Integer(), nullable=False),
    sa.Column('replacement_period_days', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'version')
    )
    with op.batch_alter_table('requirement_commercial_terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_commercial_terms_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('requirement_submission_schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fields_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'version')
    )
    with op.batch_alter_table('requirement_submission_schemas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_submission_schemas_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('candidate_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('provider_version', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank_score', sa.Float(), nullable=False),
    sa.Column('fit_band', sa.String(length=30), nullable=False),
    sa.Column('recommendation', sa.String(length=40), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'version')
    )
    with op.batch_alter_table('candidate_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_evaluations_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_evaluations_fit_band'), ['fit_band'], unique=False)

    op.create_table('candidate_eligibility',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('checked_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id')
    )
    with op.batch_alter_table('candidate_eligibility', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_eligibility_status'), ['status'], unique=False)

    op.create_table('candidate_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_profile_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('sourcing_partner_user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['sourcing_partner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id'),
    sa.UniqueConstraint('requirement_id', 'candidate_profile_id')
    )
    with op.batch_alter_table('candidate_ownership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_ownership_candidate_profile_id'), ['candidate_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_ownership_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_ownership_sourcing_partner_user_id'), ['sourcing_partner_user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('client_company_id', sa.Integer(), nullable=False),
    sa.Column('partner_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['client_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['partner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_client_company_id'), ['client_company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_partner_user_id'), ['partner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('duplicate_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('attempted_candidate_profile_id', sa.Integer(), nullable=False),
    sa.Column('existing_application_id', sa.Integer(), nullable=False),
    sa.Column('attempted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('matched_on', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['attempted_candidate_profile_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['existing_application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duplicate_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duplicate_attempts_attempted_by_user_id'), ['attempted_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicate_attempts_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('vendor_status', sa.String(length=30), nullable=False),
    sa.Column('candidate_status', sa.String(length=30), nullable=False),
    sa.Column('partner_status', sa.String(length=30), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('joined_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('placements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_placements_application_id'), ['application_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_placements_verification_status'), ['verification_status'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.Column('commercial_terms_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commercial_terms_id'], ['requirement_commercial_terms.id'], ),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payouts_placement_id'), ['placement_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payouts_status'), ['status'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_data', sa.Text(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('readiness_status', sa.String(length=30), nullable=False, server_default='not_ready'))
        batch_op.create_index(batch_op.f('ix_applications_readiness_status'), ['readiness_status'], unique=False)

    with op.batch_alter_table('requirement_partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('match_reasons', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('accepted_commercial_terms_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('viewed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_requirement_partners_accepted_terms', 'requirement_commercial_terms', ['accepted_commercial_terms_id'], ['id'])

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_process', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('submission_deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('additional_notes', sa.Text(), nullable=True))

    with op.batch_alter_table('resume_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sha256', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_resume_files_sha256'), ['sha256'], unique=False)

    with op.batch_alter_table('sourcing_partner_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recruiter_type', sa.String(length=30), nullable=False, server_default='individual'))
        batch_op.add_column(sa.Column('role_specializations', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('locations', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('employment_expertise', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('work_authorization_expertise', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('experience_ranges', sa.Text(), nullable=False, server_default='[]'))

    # Backfill local development records so pre-existing requirements remain usable.
    op.get_bind().exec_driver_sql("""
        INSERT INTO requirement_submission_schemas
            (requirement_id, version, fields_json, is_active, created_by_user_id, created_at)
        SELECT r.id, 1,
            '[{"key":"resume","label":"Resume","required":true},{"key":"candidate_name","label":"Candidate name","required":true},{"key":"email","label":"Email","required":true},{"key":"phone","label":"Phone","required":true}]',
            TRUE, r.created_by_user_id, r.created_at
        FROM requirements r
        WHERE NOT EXISTS (SELECT 1 FROM requirement_submission_schemas s WHERE s.requirement_id = r.id)
    """)
    op.get_bind().exec_driver_sql("""
        INSERT INTO requirement_commercial_terms
            (requirement_id, version, payout_model, payout_amount, currency, payment_trigger,
             payment_timeline_days, replacement_period_days, notes, is_active, created_by_user_id, created_at)
        SELECT r.id, 1, 'fixed', 0, COALESCE(r.currency, CASE WHEN r.country = 'IN' THEN 'INR' ELSE 'USD' END),
            'candidate_joined', 30, 0, 'Backfilled local development terms; client review required.', TRUE,
            r.created_by_user_id, r.created_at
        FROM requirements r
        WHERE NOT EXISTS (SELECT 1 FROM requirement_commercial_terms t WHERE t.requirement_id = r.id)
    """)
    op.get_bind().exec_driver_sql("""
        INSERT INTO candidate_availability
            (candidate_profile_id, status, available_from, last_confirmed_at, confirmed_by, updated_at)
        SELECT c.id, 'needs_reconfirmation', NULL, NULL, NULL, c.updated_at
        FROM candidate_profiles c
        WHERE NOT EXISTS (SELECT 1 FROM candidate_availability a WHERE a.candidate_profile_id = c.id)
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sourcing_partner_profiles', schema=None) as batch_op:
        batch_op.drop_column('experience_ranges')
        batch_op.drop_column('work_authorization_expertise')
        batch_op.drop_column('employment_expertise')
        batch_op.drop_column('locations')
        batch_op.drop_column('role_specializations')
        batch_op.drop_column('recruiter_type')

    with op.batch_alter_table('resume_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_files_sha256'))
        batch_op.drop_column('sha256')

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_column('additional_notes')
        batch_op.drop_column('submission_deadline')
        batch_op.drop_column('interview_process')

    with op.batch_alter_table('requirement_partners', schema=None) as batch_op:
        batch_op.drop_constraint('fk_requirement_partners_accepted_terms', type_='foreignkey')
        batch_op.drop_column('viewed_at')
        batch_op.drop_column('accepted_at')
        batch_op.drop_column('accepted_commercial_terms_id')
        batch_op.drop_column('match_reasons')
        batch_op.drop_column('match_score')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_readiness_status'))
        batch_op.drop_column('readiness_status')
        batch_op.drop_column('submission_data')

    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payouts_status'))
        batch_op.drop_index(batch_op.f('ix_payouts_placement_id'))

    op.drop_table('payouts')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('placements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placements_verification_status'))
        batch_op.drop_index(batch_op.f('ix_placements_application_id'))

    op.drop_table('placements')
    with op.batch_alter_table('duplicate_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duplicate_attempts_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_duplicate_attempts_attempted_by_user_id'))

    op.drop_table('duplicate_attempts')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_partner_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_client_company_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_application_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('candidate_ownership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_ownership_sourcing_partner_user_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_ownership_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_ownership_candidate_profile_id'))

    op.drop_table('candidate_ownership')
    with op.batch_alter_table('candidate_eligibility', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_eligibility_status'))

    op.drop_table('candidate_eligibility')
    with op.batch_alter_table('candidate_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_evaluations_fit_band'))
        batch_op.drop_index(batch_op.f('ix_candidate_evaluations_application_id'))

    op.drop_table('candidate_evaluations')
    with op.batch_alter_table('requirement_submission_schemas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_submission_schemas_requirement_id'))

    op.drop_table('requirement_submission_schemas')
    with op.batch_alter_table('requirement_commercial_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_commercial_terms_requirement_id'))

    op.drop_table('requirement_commercial_terms')
    with op.batch_alter_table('candidate_interests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_interests_status'))
        batch_op.drop_index(batch_op.f('ix_candidate_interests_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_interests_candidate_profile_id'))

    op.drop_table('candidate_interests')
    with op.batch_alter_table('candidate_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_availability_status'))

    op.drop_table('candidate_availability')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
