"""initial recruitment network schema

Revision ID: 94515b6543dc
Revises: 
Create Date: 2026-08-23 01:24:48.029369
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '94515b6543dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=160), nullable=False),
    sa.Column('company_type', sa.String(length=60), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)

    op.create_table('resume_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_name', sa.String(length=100), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_name')
    )
    op.create_table('sourcing_partner_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=160), nullable=False),
    sa.Column('agency_name', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('industries', sa.Text(), nullable=False),
    sa.Column('skill_areas', sa.Text(), nullable=False),
    sa.Column('hiring_markets', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=160), nullable=False),
    sa.Column('current_title', sa.String(length=200), nullable=False),
    sa.Column('total_experience', sa.Float(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('current_employer', sa.String(length=200), nullable=True),
    sa.Column('country_specific_data', sa.Text(), nullable=False),
    sa.Column('resume_file_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resume_file_id'], ['resume_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_profiles_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_profiles_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_profiles_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_profiles_full_name'), ['full_name'], unique=False)

    op.create_table('company_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('member_role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id')
    )
    with op.batch_alter_table('company_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_members_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_members_user_id'), ['user_id'], unique=False)

    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('state_region', sa.String(length=160), nullable=True),
    sa.Column('city', sa.String(length=160), nullable=False),
    sa.Column('work_mode', sa.String(length=20), nullable=False),
    sa.Column('employment_type', sa.String(length=40), nullable=False),
    sa.Column('min_experience', sa.Float(), nullable=False),
    sa.Column('max_experience', sa.Float(), nullable=False),
    sa.Column('required_skills', sa.Text(), nullable=False),
    sa.Column('preferred_skills', sa.Text(), nullable=False),
    sa.Column('openings', sa.Integer(), nullable=True),
    sa.Column('compensation_min', sa.Float(), nullable=True),
    sa.Column('compensation_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('compensation_type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_employment_type'), ['employment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_work_mode'), ['work_mode'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('candidate_profile_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('submission_source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'candidate_profile_id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_candidate_profile_id'), ['candidate_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_submission_source'), ['submission_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_submitted_by_user_id'), ['submitted_by_user_id'], unique=False)

    op.create_table('requirement_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('sourcing_partner_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sourcing_partner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'sourcing_partner_user_id')
    )
    with op.batch_alter_table('requirement_partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_partners_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_partners_sourcing_partner_user_id'), ['sourcing_partner_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_partners_sourcing_partner_user_id'))
        batch_op.drop_index(batch_op.f('ix_requirement_partners_requirement_id'))

    op.drop_table('requirement_partners')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_submitted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_applications_submission_source'))
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_applications_candidate_profile_id'))

    op.drop_table('applications')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_work_mode'))
        batch_op.drop_index(batch_op.f('ix_requirements_title'))
        batch_op.drop_index(batch_op.f('ix_requirements_status'))
        batch_op.drop_index(batch_op.f('ix_requirements_employment_type'))
        batch_op.drop_index(batch_op.f('ix_requirements_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_country'))
        batch_op.drop_index(batch_op.f('ix_requirements_company_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_city'))

    op.drop_table('requirements')
    with op.batch_alter_table('company_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_company_members_company_id'))

    op.drop_table('company_members')
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_full_name'))
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_email'))
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_country'))

    op.drop_table('candidate_profiles')
    op.drop_table('sourcing_partner_profiles')
    op.drop_table('resume_files')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.drop_index(batch_op.f('ix_companies_country'))

    op.drop_table('companies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###

